/**
 * Postgres DDL and schema-name helpers for the Server (Postgres) backend (#48).
 *
 * Each GnuDash book lives in its own Postgres SCHEMA (namespace) so a single
 * database can host multiple books without table-name collisions. MVP exposes
 * only DEFAULT_BOOK_ID; the per-book-schema indirection exists so multi-tenant
 * deployments (one schema per user) are additive rather than a schema redesign.
 *
 * ## Date/timestamp columns
 *
 * Date/timestamp columns are TEXT (not TIMESTAMP). The engine emits dates in
 * GnuCash's compact `YYYYMMDDHHmmss` string format (commit f51516d) and this
 * schema stores them as-is so the adapter can pass strings through without any
 * per-column translation layer. GnuCash's own Postgres backend uses TIMESTAMP,
 * but we do not interop through this schema — users import `.gnucash` SQLite /
 * XML files, not connect GnuCash desktop directly — so the column-type
 * divergence is acceptable and preferable to the alternative of translating
 * every read and write.
 *
 * ## Numeric pairs
 *
 * GnuCash stores rationals as `(num BIGINT, denom BIGINT)` pairs. All
 * numeric-pair columns are BIGINT in both SQLite (INTEGER) and Postgres so the
 * engine's values pass through unchanged.
 *
 * ## Auto-increment IDs
 *
 * SQLite `INTEGER PRIMARY KEY AUTOINCREMENT` becomes
 * `BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`; `INTEGER PRIMARY KEY`
 * becomes `BIGSERIAL PRIMARY KEY`. Both accept explicit values during import.
 * The importer is responsible for bumping the underlying sequence to
 * `MAX(id) + 1` after a bulk copy so subsequent auto-assigned IDs don't
 * collide with imported ones — that logic lives in the import route (PR 3).
 */

/** Prefix applied to every per-book Postgres schema name. */
export const BOOK_SCHEMA_PREFIX = "book_";

/**
 * Default book ID used by the MVP (single book per database). Change this
 * indirectly via a different sanitized ID once multi-book support lands — never
 * by hardcoding a schema name at a call site.
 */
export const DEFAULT_BOOK_ID = "default";

/**
 * Version stamped into `gnudash_meta.schema_version` on fresh import. Bump
 * whenever `GNUCASH_POSTGRES_DDL` changes in a backwards-incompatible way so
 * future migrations can dispatch on the old value.
 */
export const CURRENT_SCHEMA_VERSION = 1;

const BOOK_ID_PATTERN = /^[a-z][a-z0-9_]{0,62}$/;

/**
 * Validate a book ID. Book IDs become part of an unquoted Postgres identifier
 * (schema name), so anything that could break out of the schema-name syntax —
 * hyphens, quotes, semicolons, leading digits, uppercase (PG folds it) — is
 * rejected. The 63-character cap matches PG's identifier length limit once the
 * `book_` prefix is accounted for.
 *
 * @throws if `id` does not match `/^[a-z][a-z0-9_]{0,62}$/`.
 */
export function sanitizeBookId(id: string): string {
  if (typeof id !== "string" || !BOOK_ID_PATTERN.test(id)) {
    throw new Error(
      `Invalid book ID ${JSON.stringify(id)}: must match /^[a-z][a-z0-9_]{0,62}$/`
    );
  }
  return id;
}

/** Fully qualified Postgres schema name for the given book ID. */
export function bookSchemaName(bookId: string): string {
  return `${BOOK_SCHEMA_PREFIX}${sanitizeBookId(bookId)}`;
}

export function createBookSchemaSQL(bookId: string): string {
  return `CREATE SCHEMA IF NOT EXISTS ${bookSchemaName(bookId)}`;
}

export function dropBookSchemaSQL(bookId: string): string {
  return `DROP SCHEMA IF EXISTS ${bookSchemaName(bookId)} CASCADE`;
}

export function setSearchPathSQL(bookId: string): string {
  return `SET search_path TO ${bookSchemaName(bookId)}`;
}

/** INSERT statement that stamps the current schema version on a fresh book. */
export function insertSchemaVersionSQL(): string {
  return `INSERT INTO gnudash_meta (schema_version) VALUES (${CURRENT_SCHEMA_VERSION})`;
}

/**
 * CREATE TABLE statements for every GnuCash table the engine reads or writes,
 * plus the `gnudash_meta` metadata table. Mirrors `GNUCASH_SCHEMA_DDL` from
 * xml/schema.ts *and* the additional `lots` / `slots` tables the engine
 * expects (see `ENSURE_TABLES_SQL` in writable-wasm-adapter.ts) — old-format
 * files that lack those in SQLite get them added at runtime, but a fresh
 * Postgres schema must have them from the start because the engine never
 * executes schema bootstrap DDL through the Postgres adapter.
 *
 * ## NOT NULL policy
 *
 * Real .gnucash SQLite files are looser than xml/schema.ts's minimal DDL —
 * e.g. `accounts.commodity_guid` is NULL on template accounts, and most
 * `*_DEFAULT ''` columns accept explicit NULLs from older file versions.
 * An over-strict NOT NULL here produces an import failure on the first real
 * file someone uploads. This DDL therefore only carries NOT NULL where the
 * column is a foreign-key target the engine genuinely requires (account
 * guids in splits, etc.) or a numeric pair that would corrupt accounting
 * arithmetic if NULL. Everything else accepts the source value as-is, with
 * DEFAULT applied only when the column is omitted (per PG semantics).
 *
 * Apply this DDL inside the target schema via `SET search_path TO <schema>`
 * first — the caller is responsible for creating the schema.
 */
export const GNUCASH_POSTGRES_DDL = `
CREATE TABLE books (
  guid TEXT PRIMARY KEY,
  root_account_guid TEXT NOT NULL,
  root_template_guid TEXT,
  num_periods BIGINT DEFAULT 0
);

CREATE TABLE commodities (
  guid TEXT PRIMARY KEY,
  namespace TEXT NOT NULL,
  mnemonic TEXT NOT NULL,
  fullname TEXT DEFAULT '',
  cusip TEXT DEFAULT '',
  fraction BIGINT DEFAULT 100
);

CREATE TABLE accounts (
  guid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  account_type TEXT NOT NULL,
  commodity_guid TEXT,
  commodity_scu BIGINT DEFAULT 100,
  non_std_scu BIGINT DEFAULT 0,
  parent_guid TEXT,
  code TEXT DEFAULT '',
  description TEXT DEFAULT '',
  hidden BIGINT DEFAULT 0,
  placeholder BIGINT DEFAULT 0
);

CREATE TABLE transactions (
  guid TEXT PRIMARY KEY,
  currency_guid TEXT NOT NULL,
  num TEXT DEFAULT '',
  post_date TEXT NOT NULL,
  enter_date TEXT DEFAULT '',
  description TEXT DEFAULT ''
);

CREATE TABLE splits (
  guid TEXT PRIMARY KEY,
  tx_guid TEXT NOT NULL,
  account_guid TEXT NOT NULL,
  memo TEXT DEFAULT '',
  action TEXT DEFAULT '',
  reconcile_state TEXT DEFAULT 'n',
  value_num BIGINT NOT NULL,
  value_denom BIGINT NOT NULL DEFAULT 100,
  quantity_num BIGINT NOT NULL,
  quantity_denom BIGINT NOT NULL DEFAULT 100,
  lot_guid TEXT
);

CREATE TABLE prices (
  guid TEXT PRIMARY KEY,
  commodity_guid TEXT NOT NULL,
  currency_guid TEXT NOT NULL,
  date TEXT NOT NULL,
  source TEXT DEFAULT '',
  type TEXT DEFAULT '',
  value_num BIGINT NOT NULL,
  value_denom BIGINT NOT NULL DEFAULT 100
);

CREATE TABLE schedxactions (
  guid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  enabled BIGINT DEFAULT 1,
  start_date TEXT DEFAULT '',
  end_date TEXT,
  last_occur TEXT,
  num_occur BIGINT DEFAULT 0,
  rem_occur BIGINT DEFAULT 0,
  auto_create BIGINT DEFAULT 0
);

CREATE TABLE recurrences (
  id BIGSERIAL PRIMARY KEY,
  obj_guid TEXT NOT NULL,
  recurrence_mult BIGINT DEFAULT 1,
  recurrence_period_type TEXT DEFAULT 'month',
  recurrence_period_start TEXT DEFAULT ''
);

CREATE TABLE budgets (
  guid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  num_periods BIGINT DEFAULT 12
);

CREATE TABLE budget_amounts (
  id BIGSERIAL PRIMARY KEY,
  budget_guid TEXT NOT NULL,
  account_guid TEXT NOT NULL,
  period_num BIGINT NOT NULL,
  amount_num BIGINT NOT NULL,
  amount_denom BIGINT NOT NULL DEFAULT 100
);

CREATE TABLE slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obj_guid TEXT NOT NULL,
  name TEXT NOT NULL,
  slot_type BIGINT NOT NULL DEFAULT 4,
  int64_val BIGINT,
  string_val TEXT,
  double_val DOUBLE PRECISION,
  timespec_val TEXT,
  guid_val TEXT,
  numeric_val_num BIGINT,
  numeric_val_denom BIGINT,
  gdate_val TEXT
);

CREATE TABLE lots (
  guid TEXT PRIMARY KEY,
  account_guid TEXT NOT NULL,
  is_closed BIGINT DEFAULT 0
);

CREATE TABLE gnudash_meta (
  schema_version INTEGER NOT NULL
);
`;

/** Tables created by GNUCASH_POSTGRES_DDL, in definition order. */
export const GNUCASH_POSTGRES_TABLES = [
  "books",
  "commodities",
  "accounts",
  "transactions",
  "splits",
  "prices",
  "schedxactions",
  "recurrences",
  "budgets",
  "budget_amounts",
  "slots",
  "lots",
  "gnudash_meta",
] as const;
