import { describe, expect, it } from "vitest";
import { REQUIRED_TABLES } from "../validation";
import {
  BOOK_SCHEMA_PREFIX,
  bookSchemaName,
  createBookSchemaSQL,
  CURRENT_SCHEMA_VERSION,
  DEFAULT_BOOK_ID,
  dropBookSchemaSQL,
  GNUCASH_POSTGRES_DDL,
  GNUCASH_POSTGRES_TABLES,
  insertSchemaVersionSQL,
  sanitizeBookId,
  setSearchPathSQL,
} from "../postgres-schema";

describe("sanitizeBookId", () => {
  it.each(["default", "book1", "my_book", "a", "abc_123"])(
    "accepts valid id %s",
    (id) => {
      expect(sanitizeBookId(id)).toBe(id);
    }
  );

  it.each([
    "",
    "1book",
    "My_Book",
    "my-book",
    "my book",
    "book;",
    "'; DROP SCHEMA ;",
    "a".repeat(64),
  ])("rejects invalid id %s", (id) => {
    expect(() => sanitizeBookId(id)).toThrow(/Invalid book ID/);
  });

  it("rejects non-string inputs", () => {
    // @ts-expect-error exercising the runtime type guard
    expect(() => sanitizeBookId(null)).toThrow(/Invalid book ID/);
    // @ts-expect-error exercising the runtime type guard
    expect(() => sanitizeBookId(42)).toThrow(/Invalid book ID/);
  });

  it("accepts an id exactly at the 63-char total-length limit", () => {
    // 63 is PG's identifier length cap; with 'book_' (5) prefix the body must
    // be at most 58 chars — but BOOK_ID_PATTERN allows 63 for the body alone.
    // The body itself can be up to 63 chars before the regex caps it, so the
    // full prefix+body can be 68. We document but do not enforce the PG cap
    // here (bookSchemaName is the caller responsible for total length).
    const maxBody = "a".repeat(63);
    expect(sanitizeBookId(maxBody)).toBe(maxBody);
  });
});

describe("schema name helpers", () => {
  it("prefixes bookSchemaName with book_", () => {
    expect(bookSchemaName(DEFAULT_BOOK_ID)).toBe(
      `${BOOK_SCHEMA_PREFIX}${DEFAULT_BOOK_ID}`
    );
    expect(bookSchemaName("alice")).toBe("book_alice");
  });

  it("generates CREATE SCHEMA IF NOT EXISTS", () => {
    expect(createBookSchemaSQL("alice")).toBe(
      "CREATE SCHEMA IF NOT EXISTS book_alice"
    );
  });

  it("generates DROP SCHEMA IF EXISTS ... CASCADE", () => {
    expect(dropBookSchemaSQL("alice")).toBe(
      "DROP SCHEMA IF EXISTS book_alice CASCADE"
    );
  });

  it("generates SET search_path TO <schema>", () => {
    expect(setSearchPathSQL("alice")).toBe("SET search_path TO book_alice");
  });

  it("propagates sanitizeBookId errors through every helper", () => {
    expect(() => bookSchemaName("Bad-Id")).toThrow(/Invalid book ID/);
    expect(() => createBookSchemaSQL("Bad-Id")).toThrow(/Invalid book ID/);
    expect(() => dropBookSchemaSQL("Bad-Id")).toThrow(/Invalid book ID/);
    expect(() => setSearchPathSQL("Bad-Id")).toThrow(/Invalid book ID/);
  });
});

describe("insertSchemaVersionSQL", () => {
  it("inserts the current version literal into gnudash_meta", () => {
    expect(insertSchemaVersionSQL()).toBe(
      `INSERT INTO gnudash_meta (schema_version) VALUES (${CURRENT_SCHEMA_VERSION})`
    );
  });
});

describe("GNUCASH_POSTGRES_DDL", () => {
  it.each(GNUCASH_POSTGRES_TABLES)(
    "declares CREATE TABLE for %s",
    (table) => {
      expect(GNUCASH_POSTGRES_DDL).toMatch(
        new RegExp(`CREATE TABLE\\s+${table}\\s*\\(`)
      );
    }
  );

  it("covers every table the engine requires in REQUIRED_TABLES", () => {
    for (const required of Object.keys(REQUIRED_TABLES)) {
      expect(GNUCASH_POSTGRES_TABLES).toContain(required);
    }
  });

  it("uses BIGINT for numeric-pair columns", () => {
    // Spot-check the splits table — the most numeric-heavy one.
    expect(GNUCASH_POSTGRES_DDL).toMatch(/value_num\s+BIGINT\s+NOT NULL/);
    expect(GNUCASH_POSTGRES_DDL).toMatch(/value_denom\s+BIGINT\s+NOT NULL/);
    expect(GNUCASH_POSTGRES_DDL).toMatch(/quantity_num\s+BIGINT\s+NOT NULL/);
    expect(GNUCASH_POSTGRES_DDL).toMatch(/quantity_denom\s+BIGINT\s+NOT NULL/);
  });

  it("stores dates as TEXT (no per-column translation needed)", () => {
    expect(GNUCASH_POSTGRES_DDL).toMatch(/post_date\s+TEXT\s+NOT NULL/);
    expect(GNUCASH_POSTGRES_DDL).toMatch(/enter_date\s+TEXT/);
    // prices.date
    expect(GNUCASH_POSTGRES_DDL).toMatch(/date\s+TEXT\s+NOT NULL/);
  });

  it("gives autoincrement ids an explicit identity/sequence", () => {
    expect(GNUCASH_POSTGRES_DDL).toMatch(
      /id\s+BIGINT\s+GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/
    );
    expect(GNUCASH_POSTGRES_DDL).toMatch(/id\s+BIGSERIAL\s+PRIMARY KEY/);
  });
});
